import sys

import pytest
from conftest import git

from taskreplay import mine
from taskreplay.scoring import verify_task
from taskreplay.tasks import load

TEST_CMD = f'"{sys.executable}" -m pytest -q -p no:cacheprovider {{test_files}}'


@pytest.mark.parametrize(
    "path, is_test, is_code",
    [
        ("tests/test_calc.py", True, False),
        ("pkg/calc_test.py", True, False),
        ("src/app.test.ts", True, False),
        ("server/handler_test.go", True, False),
        ("src/main/FooTest.java", True, False),
        ("calc.py", False, True),
        ("src/lib.rs", False, True),
        ("README.md", False, False),
        ("tests/data.json", False, False),
    ],
)
def test_classification(path, is_test, is_code):
    assert mine.is_test_file(path) is is_test
    assert mine.is_code_file(path) is is_code


def test_message_helpers():
    msg = "fix(parser): handle empty input\n\nDetails here.\n\nSigned-off-by: Someone <x@example.invalid>\nCo-Authored-By: Bot <b@example.invalid>"
    cleaned = mine.clean_message(msg)
    assert "Signed-off-by" not in cleaned and "Co-Authored-By" not in cleaned
    assert cleaned.startswith("fix(parser): handle empty input")
    assert mine.tags_for("fix(parser): x") == ["bugfix"]
    assert mine.tags_for("feat: y") == ["feature"]
    assert mine.tags_for("Update things") == []
    assert mine.slug("fix: Handle EMPTY input!") == "handle-empty-input"


def test_find_candidates(toy_repo):
    cands = mine.find_candidates(toy_repo.path)
    commits = [c.commit for c in cands]
    assert commits == [toy_repo.fix, toy_repo.noop]  # docs-only and root commits are skipped
    fix = cands[0]
    assert fix.parent == toy_repo.base
    assert fix.code_files == ["calc.py"] and fix.test_files == ["tests/test_calc.py"]
    assert "Signed-off-by" not in fix.message


def test_mine_verifies(toy_repo):
    logs = []
    tasks = mine.mine(toy_repo.path, since=None, test_cmd=TEST_CMD, log=logs.append)
    assert [t.solution for t in tasks] == [toy_repo.fix]
    t = tasks[0]
    assert t.base == toy_repo.base
    assert t.tags == ["bugfix"]
    assert t.prompt.startswith("fix: add returns the sum")
    assert t.hidden_tests[0].path == "tests/test_calc.py"
    assert "tests/test_calc.py" in t.test
    assert any("already pass at parent" in line for line in logs)
    assert verify_task(t).ok


def test_mine_since_filters_everything(toy_repo):
    assert mine.find_candidates(toy_repo.path, since="2090-01-01") == []


def test_mine_cli_writes_editable_task_file(tmp_path, toy_repo):
    from taskreplay.cli import main

    out = tmp_path / "mined" / "tasks.yaml"
    assert main(["mine", str(toy_repo.path), "--test-cmd", TEST_CMD, "--out", str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("# Generated by `taskreplay mine`")
    tf = load(out)
    assert len(tf.tasks) == 1 and tf.tasks[0].repo == toy_repo.path.resolve()
    # refuses to overwrite without --force
    assert main(["mine", str(toy_repo.path), "--test-cmd", TEST_CMD, "--out", str(out)]) == 2
    # the main checkout was not touched by the verification runs
    assert git(toy_repo.path, "status", "--porcelain") == ""
    assert git(toy_repo.path, "rev-parse", "HEAD") == toy_repo.noop


def test_mine_list(capsys, toy_repo):
    from taskreplay.cli import main

    assert main(["mine", str(toy_repo.path), "--list"]) == 0
    out = capsys.readouterr().out
    assert toy_repo.fix[:8] in out and "2 candidate(s)" in out
