"""Command line interface."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from . import __version__, engine, gitutil, mine, report, scoring
from .runners import RunnerConfigError, resolve_runners
from .tasks import TaskFileError, dump, load


def _split(value: str | None) -> list[str]:
    return [v.strip() for v in (value or "").split(",") if v.strip()]


def _load_tasks(args) -> tuple[list, dict]:
    tf = load(args.tasks)
    runners_cfg = dict(tf.runners)
    if getattr(args, "config", None):
        data = yaml.safe_load(Path(args.config).read_text(encoding="utf-8")) or {}
        extra = data.get("runners", data) if isinstance(data, dict) else None
        if not isinstance(extra, dict):
            raise TaskFileError(f"{args.config}: expected a mapping of runners")
        runners_cfg.update(extra)
    tasks = tf.tasks
    only = _split(getattr(args, "only", None))
    if only:
        missing = set(only) - {t.id for t in tasks}
        if missing:
            raise TaskFileError(f"unknown task id(s): {', '.join(sorted(missing))}")
        tasks = [t for t in tasks if t.id in only]
    return tasks, runners_cfg


def cmd_run(args) -> int:
    tasks, runners_cfg = _load_tasks(args)
    names = _split(args.runners)
    if not names:
        print("error: --runners is required, e.g. --runners claude,codex", file=sys.stderr)
        return 2
    runners = resolve_runners(names, runners_cfg)
    if args.attempts < 1:
        print("error: --attempts must be at least 1", file=sys.stderr)
        return 2
    runs = engine.plan(tasks, runners, args.attempts, args.max_tasks)
    if not runs:
        print("nothing to run")
        return 0
    if args.dry_run:
        print(f"dry run: {len(runs)} run(s) would be executed, nothing is started\n")
        for line in engine.describe_plan(runs):
            print(line)
        if args.max_cost is not None:
            print(f"\nbudget: stop after ${args.max_cost:.2f} of reported or estimated cost")
        return 0
    for t in {t.id: t for t in (r.task for r in runs)}.values():
        if not gitutil.is_repo(t.repo):
            print(f"error: task {t.id!r}: {t.repo} is not a git repository", file=sys.stderr)
            return 2
    print(
        f"running {len(runs)} run(s). Agent CLIs and API runners use real quota or money."
        + (f" Budget: ${args.max_cost:.2f}." if args.max_cost is not None else " No --max-cost set.")
    )
    eng = engine.Engine(Path(args.out), max_cost=args.max_cost, keep=args.keep)
    records = eng.run(runs)
    print(f"\nresults: {eng.results_file}")
    if records:
        print()
        print(report.render_text(records))
    return 0


def cmd_report(args) -> int:
    paths = args.paths or ["results"]
    for p in paths:
        if not Path(p).exists():
            print(f"error: {p} does not exist", file=sys.stderr)
            return 2
    records = report.load_results(paths)
    runner_filter = _split(args.runners)
    if runner_filter:
        records = [r for r in records if r["runner"] in runner_filter]
    print(report.render_text(records))
    if not records:
        return 1
    if args.html != "-":
        first = Path(paths[0])
        out = Path(args.html) if args.html else (first if first.is_dir() else first.parent) / "report.html"
        out.write_text(report.render_html(records, title=args.title), encoding="utf-8")
        print(f"\nHTML report: {out}")
    return 0


def cmd_mine(args) -> int:
    repo = Path(args.repo).resolve()
    if not gitutil.is_repo(repo):
        print(f"error: {repo} is not a git repository", file=sys.stderr)
        return 2
    if args.list:
        cands = mine.find_candidates(repo, args.since, args.ref, args.max_scan)
        for c in cands:
            print(f"{c.commit[:8]}  {c.subject}\n    code:  {', '.join(c.code_files)}\n    tests: {', '.join(c.test_files)}")
        print(f"{len(cands)} candidate(s); run without --list to verify them and write tasks")
        return 0
    out = Path(args.out)
    if out.exists() and not args.force:
        print(f"error: {out} exists; use --force to overwrite or --out to choose another file", file=sys.stderr)
        return 2
    tasks = mine.mine(repo, args.since, args.test_cmd, args.ref, args.limit, args.max_scan)
    if not tasks:
        print("no verified tasks found; nothing written")
        return 1
    header = (
        "# Generated by `taskreplay mine`. Prompts are taken from commit messages:\n"
        "# edit them so they describe the task the way you would ask an agent.\n"
        "# hidden_tests are restored from the solution commit before scoring.\n"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dump(tasks, out.resolve().parent, header), encoding="utf-8")
    print(f"wrote {len(tasks)} task(s) to {out}")
    return 0


def cmd_validate(args) -> int:
    tasks, _ = _load_tasks(args)
    bad = 0
    for t in tasks:
        v = scoring.verify_task(t)
        base = {True: "fails at base", False: "PASSES at base (task is trivial)", None: "base not checked"}[v.fails_at_base]
        sol = {True: "passes at solution", False: "FAILS at solution", None: "no solution commit"}[v.passes_at_solution]
        status = "ok " if v.ok else "BAD"
        bad += 0 if v.ok else 1
        print(f"{status} {t.id}: {base}; {sol}" + (f"; {v.detail}" if v.detail else ""))
    return 1 if bad else 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="taskreplay",
        description="Benchmark coding agents on your own past tasks, replayed in isolated git worktrees.",
    )
    p.add_argument("--version", action="version", version=f"taskreplay {__version__}")
    sub = p.add_subparsers(dest="command", required=True)

    r = sub.add_parser("run", help="replay tasks with one or more runners")
    r.add_argument("tasks", help="task file (tasks.yaml)")
    r.add_argument("--runners", required=True, help="comma separated runner names, e.g. claude,codex")
    r.add_argument("--attempts", type=int, default=1, help="attempts per task and runner (default 1)")
    r.add_argument("--out", default="results", help="results directory (default: results)")
    r.add_argument("--config", help="extra YAML file with a 'runners:' mapping")
    r.add_argument("--only", help="comma separated task ids to run")
    r.add_argument("--max-tasks", type=int, help="run at most this many tasks")
    r.add_argument("--max-cost", type=float, help="stop starting new runs once this many USD are spent")
    r.add_argument("--keep", action="store_true", help="keep worktrees for inspection")
    r.add_argument("--dry-run", action="store_true", help="show what would run and exit")
    r.set_defaults(func=cmd_run)

    rep = sub.add_parser("report", help="summarise results and write an HTML report")
    rep.add_argument("paths", nargs="*", help="result files or directories (default: results)")
    rep.add_argument("--html", help="HTML output path (default: <results dir>/report.html; '-' to skip)")
    rep.add_argument("--title", default="taskreplay report")
    rep.add_argument("--runners", help="only include these runners")
    rep.set_defaults(func=cmd_report)

    m = sub.add_parser("mine", help="propose tasks from commits that change code and tests")
    m.add_argument("repo", help="path to the git repository")
    m.add_argument("--since", help="only commits after this date, e.g. 2026-01-01 or '3 months ago'")
    m.add_argument("--ref", default="HEAD", help="branch or ref to scan (default HEAD)")
    m.add_argument(
        "--test-cmd",
        default=mine.DEFAULT_TEST_CMD,
        help="test command; {test_files} is replaced by the commit's test files (default: %(default)s)",
    )
    m.add_argument("--out", default="tasks.yaml", help="output task file (default tasks.yaml)")
    m.add_argument("--force", action="store_true", help="overwrite --out")
    m.add_argument("--limit", type=int, default=20, help="maximum number of tasks (default 20)")
    m.add_argument("--max-scan", type=int, default=500, help="maximum commits to scan (default 500)")
    m.add_argument("--list", action="store_true", help="only list candidates, run no tests")
    m.set_defaults(func=cmd_mine)

    v = sub.add_parser("validate", help="check that each task fails at base and passes at its solution")
    v.add_argument("tasks", help="task file")
    v.add_argument("--only", help="comma separated task ids")
    v.set_defaults(func=cmd_validate)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except (TaskFileError, RunnerConfigError, gitutil.GitError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
